Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,15 +2,9 @@ name: CI/CD MLflow Tebu
 
 on:
   push:
-    branches:
-      - main
+    branches: [main]
   pull_request:
-    branches:
-      - main
-
-env:
-  xlx_url: "CI/data_train.xlsx"
-  target: "Ton"
+    branches: [main]
 
 jobs:
   build:
@@ -19,46 +13,47 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up Python 3.12.7
+      - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.12.7"
-      
-      - name: Setup MLflow Environment
+          python-version: "3.10"
+
+      - name: Set MLflow Local Tracking URI
         run: |
           mkdir -p CI/mlruns
-          chmod -R 777 CI/mlruns
           echo "MLFLOW_TRACKING_URI=file://$(pwd)/CI/mlruns" >> $GITHUB_ENV
-      
+
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip
+          pip install --upgrade pip
           pip install mlflow pandas scikit-learn openpyxl
-      
-      - name: Verify Files Exist
+
+      - name: Verify files exist
         working-directory: ./CI
         run: |
           ls -la
-          test -f data_train.xlsx || (echo "Data train not found!" && exit 1)
-          test -f testing.xlsx || (echo "Testing data not found!" && exit 1)
-          test -f preprocessing.py || (echo "Preprocessing script not found!" && exit 1)
-      
-      - name: Run mlflow project
+          test -f MLproject || (echo "Missing MLproject" && exit 1)
+          test -f modeling.py || (echo "Missing modeling.py" && exit 1)
+          test -f data_train.xlsx || (echo "Missing data" && exit 1)
+          test -f testing.xlsx || (echo "Missing testing data" && exit 1)
+
+      - name: Run MLflow project
         working-directory: ./CI
         run: |
-          mlflow run . --env-manager=local || (echo "MLflow run failed!" && exit 1)
-      
-      - name: Get latest MLflow run_id
+          mlflow run . --env-manager=local
+
+      - name: Get latest run ID
         id: get_run_id
         working-directory: ./CI
         run: |
           RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | awk -F'/' '{print $3}')
-          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT
-          echo "Latest run_id: ${RUN_ID}"
-      
-      - name: Build Docker Model
+          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
+          echo "Latest run_id: $RUN_ID"
+
+      - name: Build Docker model
+        working-directory: ./CI
         run: |
-          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" --name sugarcane-model
+          mlflow models build-docker --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/random_forest_final_model" --name sugarcane-model
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
